In [2]:
import streamlit as st
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="Superstore!!!", page_icon=":bar_chart:",layout="wide")

st.title(" :bar_chart: Wasoko Super Store Dashboard")
st.markdown('<style>div.block-container{padding-top:1rem;}</style>',unsafe_allow_html=True)

st.markdown("To upload file the column names should read as : day_date, Region, Branch, City, Sub Class, product_description, sell_price_usd. "
            "The Branch represents the Country Name while the Sub Class is the product category")
fl = st.file_uploader(":file_folder: Upload a file",type=(["csv","txt","xlsx","xls"]))
if fl is not None:
    filename = fl.name
    st.write(filename)
    df = pd.read_excel(filename) #, encoding = "ISO-8859-1"
else:
    # os.chdir("D:\\kulea_projects")
    # df = pd.read_excel("Sample_Superstore.xls") #, encoding = "ISO-8859-1
    data_url = 'https://drive.google.com/uc?id=1cvJjtauWfchhN7ZiWrkUCuMlABQ0xBzs'
    # https://docs.google.com/spreadsheets/d/1cvJjtauWfchhN7ZiWrkUCuMlABQ0xBzs/edit?usp=sharing&ouid=103208506414606339610&rtpof=true&sd=true
    # df = pd.read_excel("D:\\kulea_projects\\wasoko_retail_prices.xlsx")
    df = pd.read_excel(data_url, sheet_name=0)
    df.head()

In [3]:
df.head()

,day_date,Region,Country,Branch,Sub Class,product_description,sell_price_usd
0,2023-07-11,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
1,2023-07-10,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
2,2023-07-09,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
3,2023-07-08,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
4,2023-07-07,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394

In [4]:
col1, col2 = st.columns((2))
df["Order Date"] = pd.to_datetime(df["day_date"])
df.head()

,day_date,Region,Country,Branch,Sub Class,product_description,sell_price_usd,Order Date
0,2023-07-11,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-11
1,2023-07-10,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-10
2,2023-07-09,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-09
3,2023-07-08,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-08
4,2023-07-07,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-07

In [5]:
# Getting the min and max date 
startDate = pd.to_datetime(df["Order Date"]).min()
endDate = pd.to_datetime(df["Order Date"]).max()
df.head()

,day_date,Region,Country,Branch,Sub Class,product_description,sell_price_usd,Order Date
0,2023-07-11,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-11
1,2023-07-10,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-10
2,2023-07-09,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-09
3,2023-07-08,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-08
4,2023-07-07,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-07

In [6]:
with col1:
    date1 = pd.to_datetime(st.date_input("Start Date", startDate))

with col2:
    date2 = pd.to_datetime(st.date_input("End Date", endDate))

df = df[(df["Order Date"] >= date1) & (df["Order Date"] <= date2)].copy()
df.head()

,day_date,Region,Country,Branch,Sub Class,product_description,sell_price_usd,Order Date
0,2023-07-11,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-11
1,2023-07-10,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-10
2,2023-07-09,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-09
3,2023-07-08,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-08
4,2023-07-07,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394,2023-07-07

In [7]:
st.sidebar.header("Choose your filter: ")
# Create for Region
region = st.sidebar.multiselect("Pick your Region", df["Region"].unique())
if not region:
    df2 = df.copy()
else:
    df2 = df[df["Region"].isin(region)]

In [4]:
import streamlit as st
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')
@st.cache_data
def get_data():
    fl = st.file_uploader(":file_folder: Upload a file",type=(["csv","txt","xlsx","xls"]))
    if fl is not None:
        filename = fl.name
        st.write(filename)
        df = pd.read_excel(filename) #, encoding = "ISO-8859-1"
    else:
        # os.chdir("D:\\kulea_projects")
        # df = pd.read_excel("Sample_Superstore.xls") #, encoding = "ISO-8859-1
        data_url = 'https://drive.google.com/uc?id=1cvJjtauWfchhN7ZiWrkUCuMlABQ0xBzs'
        # https://docs.google.com/spreadsheets/d/1cvJjtauWfchhN7ZiWrkUCuMlABQ0xBzs/edit?usp=sharing&ouid=103208506414606339610&rtpof=true&sd=true
        # df = pd.read_excel("D:\\kulea_projects\\wasoko_retail_prices.xlsx")
        df = pd.read_excel(data_url, sheet_name=0)
    return df 
# data_url = 'https://drive.google.com/uc?id=1cvJjtauWfchhN7ZiWrkUCuMlABQ0xBzs'
# df = pd.read_excel(data_url)
df = get_data()
df.head()

2023-08-16 16:04:58.193 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-08-16 16:04:58.196 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

,day_date,Region,Country,Branch,Sub Class,product_description,sell_price_usd
0,2023-07-11,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
1,2023-07-10,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
2,2023-07-09,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
3,2023-07-08,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394
4,2023-07-07,Africa,Kenya,Eldoret,Wheat Flour & Home Baking Flour,210 Home Baking Flour 2Kg x 12,16.439394